language: go
sudo: false

go:
  - 1.10.3

before_install:
  - go get -u golang.org/x/vgo

script:
  - vgo mod -vendor
  - mkdir -p ./v
  - mv ./vendor ./v/src
  - export GOPATH=$GOPATH:$PWD/v
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
